// lib/mockData.js
// All mock data for Dhara Sanket AI dashboard.
// Replace these exports with real API calls to your FastAPI backend later.

export const stats = [
  {
    id: 'total-projects',
    label: 'Total Projects',
    value: 47,
    trend: '+12%',
    trendUp: true,
    icon: 'projects',
  },
  {
    id: 'districts',
    label: 'Districts Covered',
    value: 5,
    trend: '+2',
    trendUp: true,
    icon: 'districts',
  },
  {
    id: 'land-records',
    label: 'Land Records Analyzed',
    value: '12,847',
    trend: '+1,240',
    trendUp: true,
    icon: 'records',
  },
  {
    id: 'accuracy',
    label: 'Monitoring Accuracy',
    value: '96.4%',
    trend: '+1.2%',
    trendUp: true,
    icon: 'accuracy',
  },
];

export const projects = [
  {
    id: 'PRJ-001',
    name: 'Bhopal Smart City Ring Road Extension',
    district: 'Bhopal',
    area: '245.8 ha',
    status: 'In Progress',
    risk: 'high',
    startDate: '2026-03-15',
    landRecords: 1842,
    progress: 35,
  },
  {
    id: 'PRJ-002',
    name: 'Indore Metro Phase-II Land Acquisition',
    district: 'Indore',
    area: '182.3 ha',
    status: 'In Progress',
    risk: 'medium',
    startDate: '2026-01-20',
    landRecords: 1356,
    progress: 58,
  },
  {
    id: 'PRJ-003',
    name: 'Dewas Industrial Corridor Development',
    district: 'Dewas',
    area: '520.1 ha',
    status: 'Planning',
    risk: 'low',
    startDate: '2026-06-01',
    landRecords: 2104,
    progress: 12,
  },
  {
    id: 'PRJ-004',
    name: 'Raisen Highway Bypass Construction',
    district: 'Raisen',
    area: '98.7 ha',
    status: 'In Progress',
    risk: 'high',
    startDate: '2026-02-10',
    landRecords: 876,
    progress: 42,
  },
  {
    id: 'PRJ-005',
    name: 'Sehore Agricultural Zone Reallocation',
    district: 'Sehore',
    area: '310.4 ha',
    status: 'Review',
    risk: 'medium',
    startDate: '2026-04-22',
    landRecords: 1589,
    progress: 68,
  },
  {
    id: 'PRJ-006',
    name: 'Bhopal Lake Front Urban Renewal',
    district: 'Bhopal',
    area: '75.2 ha',
    status: 'In Progress',
    risk: 'high',
    startDate: '2026-05-08',
    landRecords: 634,
    progress: 25,
  },
  {
    id: 'PRJ-007',
    name: 'Indore SEZ Phase-III Expansion',
    district: 'Indore',
    area: '420.0 ha',
    status: 'Approved',
    risk: 'low',
    startDate: '2026-07-15',
    landRecords: 2890,
    progress: 5,
  },
  {
    id: 'PRJ-008',
    name: 'Dewas Solar Park Land Acquisition',
    district: 'Dewas',
    area: '680.5 ha',
    status: 'In Progress',
    risk: 'medium',
    startDate: '2026-02-28',
    landRecords: 1245,
    progress: 51,
  },
  {
    id: 'PRJ-009',
    name: 'Raisen Tribal Rehabilitation Settlement',
    district: 'Raisen',
    area: '156.3 ha',
    status: 'Review',
    risk: 'high',
    startDate: '2026-01-05',
    landRecords: 945,
    progress: 72,
  },
  {
    id: 'PRJ-010',
    name: 'Sehore Water Pipeline Corridor',
    district: 'Sehore',
    area: '89.6 ha',
    status: 'In Progress',
    risk: 'low',
    startDate: '2026-08-01',
    landRecords: 412,
    progress: 18,
  },
  {
    id: 'PRJ-011',
    name: 'Bhopal Eastern Freight Corridor',
    district: 'Bhopal',
    area: '345.2 ha',
    status: 'Planning',
    risk: 'medium',
    startDate: '2026-09-10',
    landRecords: 1678,
    progress: 8,
  },
  {
    id: 'PRJ-012',
    name: 'Indore Riverfront Development',
    district: 'Indore',
    area: '128.9 ha',
    status: 'In Progress',
    risk: 'high',
    startDate: '2026-04-01',
    landRecords: 756,
    progress: 44,
  },
];

export const alerts = [
  {
    id: 'ALT-001',
    title: 'Ownership Dispute Detected',
    project: 'Bhopal Smart City Ring Road Extension',
    severity: 'high',
    time: '12 min ago',
    description: 'Multiple ownership claims found for Survey No. 234/1A in Kolar area.',
  },
  {
    id: 'ALT-002',
    title: 'Land Use Violation',
    project: 'Raisen Highway Bypass Construction',
    severity: 'high',
    time: '34 min ago',
    description: 'Agricultural land re-classified without proper documentation.',
  },
  {
    id: 'ALT-003',
    title: 'Encroachment Alert',
    project: 'Bhopal Lake Front Urban Renewal',
    severity: 'high',
    time: '1 hr ago',
    description: 'Unauthorized construction detected on acquired parcel BPL-045.',
  },
  {
    id: 'ALT-004',
    title: 'Document Mismatch',
    project: 'Indore Metro Phase-II Land Acquisition',
    severity: 'medium',
    time: '2 hrs ago',
    description: 'Registry records do not match revenue records for 3 parcels.',
  },
  {
    id: 'ALT-005',
    title: 'Price Anomaly Flagged',
    project: 'Sehore Agricultural Zone Reallocation',
    severity: 'medium',
    time: '3 hrs ago',
    description: 'Market value deviates by 42% from government circle rate.',
  },
  {
    id: 'ALT-006',
    title: 'Survey Boundary Update',
    project: 'Dewas Industrial Corridor Development',
    severity: 'low',
    time: '5 hrs ago',
    description: 'Digital survey boundaries updated for 12 parcels in Sector 4.',
  },
  {
    id: 'ALT-007',
    title: 'Compliance Check Passed',
    project: 'Indore SEZ Phase-III Expansion',
    severity: 'low',
    time: '6 hrs ago',
    description: 'Environmental clearance documents verified successfully.',
  },
  {
    id: 'ALT-008',
    title: 'Tribal Land Classification Issue',
    project: 'Raisen Tribal Rehabilitation Settlement',
    severity: 'high',
    time: '8 hrs ago',
    description: 'Schedule V land parcels require additional governmental approval.',
  },
];

export const riskDistribution = {
  high: 5,
  medium: 3,
  low: 4,
};

export const projectsByDistrict = [
  { district: 'Bhopal', count: 3 },
  { district: 'Indore', count: 3 },
  { district: 'Dewas', count: 2 },
  { district: 'Raisen', count: 2 },
  { district: 'Sehore', count: 2 },
];

export const projectTrend = [
  { month: 'Jan', count: 2 },
  { month: 'Feb', count: 4 },
  { month: 'Mar', count: 5 },
  { month: 'Apr', count: 7 },
  { month: 'May', count: 8 },
  { month: 'Jun', count: 9 },
  { month: 'Jul', count: 10 },
  { month: 'Aug', count: 11 },
  { month: 'Sep', count: 12 },
];

export const hotspots = [
  { x: 55, y: 35, risk: 'high', label: 'Bhopal North', district: 'Bhopal' },
  { x: 48, y: 50, risk: 'high', label: 'Bhopal Central', district: 'Bhopal' },
  { x: 60, y: 60, risk: 'medium', label: 'Bhopal East', district: 'Bhopal' },
  { x: 20, y: 40, risk: 'high', label: 'Indore West', district: 'Indore' },
  { x: 28, y: 55, risk: 'medium', label: 'Indore South', district: 'Indore' },
  { x: 15, y: 30, risk: 'low', label: 'Indore North', district: 'Indore' },
  { x: 38, y: 25, risk: 'low', label: 'Dewas Central', district: 'Dewas' },
  { x: 42, y: 35, risk: 'medium', label: 'Dewas East', district: 'Dewas' },
  { x: 68, y: 40, risk: 'high', label: 'Raisen West', district: 'Raisen' },
  { x: 75, y: 55, risk: 'high', label: 'Raisen South', district: 'Raisen' },
  { x: 50, y: 72, risk: 'low', label: 'Sehore Central', district: 'Sehore' },
  { x: 58, y: 80, risk: 'low', label: 'Sehore South', district: 'Sehore' },
];

export const parcels = [
  {
    id: 'PCL-BPL-001',
    name: 'Survey No. 234/1A, Kolar',
    district: 'Bhopal',
    area: '12.5 ha',
    riskScore: 87,
    riskFactors: {
      ownershipDispute: 92,
      documentMismatch: 78,
      encroachment: 85,
      landUseViolation: 65,
      priceAnomaly: 45,
    },
    owner: 'Multiple Claimants',
    landUse: 'Residential / Agricultural (Disputed)',
    lastUpdated: '2026-09-15',
  },
  {
    id: 'PCL-IND-001',
    name: 'Khasra No. 45/2, Rau',
    district: 'Indore',
    area: '8.2 ha',
    riskScore: 54,
    riskFactors: {
      ownershipDispute: 30,
      documentMismatch: 72,
      encroachment: 15,
      landUseViolation: 60,
      priceAnomaly: 55,
    },
    owner: 'Rajesh Sharma',
    landUse: 'Commercial',
    lastUpdated: '2026-09-14',
  },
  {
    id: 'PCL-DWS-001',
    name: 'Plot 78-B, Industrial Area',
    district: 'Dewas',
    area: '45.0 ha',
    riskScore: 22,
    riskFactors: {
      ownershipDispute: 10,
      documentMismatch: 15,
      encroachment: 5,
      landUseViolation: 30,
      priceAnomaly: 25,
    },
    owner: 'MP State Industrial Dev. Corp.',
    landUse: 'Industrial',
    lastUpdated: '2026-09-13',
  },
  {
    id: 'PCL-RSN-001',
    name: 'Survey No. 112, Bareli',
    district: 'Raisen',
    area: '18.7 ha',
    riskScore: 79,
    riskFactors: {
      ownershipDispute: 85,
      documentMismatch: 60,
      encroachment: 90,
      landUseViolation: 75,
      priceAnomaly: 40,
    },
    owner: 'Tribal Community (Schedule V)',
    landUse: 'Forest / Agricultural',
    lastUpdated: '2026-09-12',
  },
];

export const reportStats = [
  { label: 'Total Reports Generated', value: 128, icon: 'report' },
  { label: 'Alerts Resolved', value: 89, icon: 'resolved' },
  { label: 'Pending Reviews', value: 14, icon: 'pending' },
  { label: 'Compliance Score', value: '91.2%', icon: 'compliance' },
];

// Multi-Scale India Geospatial Dataset
// Scale Level 1: Pan-India State Heatmap Data
export const indiaStatesRisk = [
  {
    id: 'MP',
    name: 'Madhya Pradesh',
    code: 'IN-MP',
    riskScore: 74,
    riskLevel: 'high',
    activeProjects: 47,
    delayedProjects: 19,
    capitalAtRiskCr: 3420,
    avgDelayMonths: 8.4,
    primaryBottleneck: 'Multi-party Title Disputes & FRA Gram Sabha',
    centerCoords: [48, 52],
    path: 'M 40,40 L 58,38 L 65,48 L 62,60 L 46,65 L 36,54 Z',
    topDistricts: ['Bhopal', 'Indore', 'Raisen', 'Dewas', 'Sehore'],
  },
  {
    id: 'MH',
    name: 'Maharashtra',
    code: 'IN-MH',
    riskScore: 82,
    riskLevel: 'very-high',
    activeProjects: 64,
    delayedProjects: 31,
    capitalAtRiskCr: 8150,
    avgDelayMonths: 11.2,
    primaryBottleneck: 'Solatium Rate Litigation & Urban Corridor ROW',
    centerCoords: [38, 66],
    path: 'M 35,56 L 52,60 L 54,72 L 40,78 L 30,68 Z',
    topDistricts: ['Mumbai Metro', 'Pune', 'Nagpur', 'Nashik', 'Thane'],
  },
  {
    id: 'UP',
    name: 'Uttar Pradesh',
    code: 'IN-UP',
    riskScore: 68,
    riskLevel: 'high',
    activeProjects: 58,
    delayedProjects: 22,
    capitalAtRiskCr: 5940,
    avgDelayMonths: 7.8,
    primaryBottleneck: 'Circle Rate vs Market Rate Discrepancies',
    centerCoords: [52, 34],
    path: 'M 44,28 L 64,30 L 68,40 L 52,44 L 42,36 Z',
    topDistricts: ['Lucknow', 'Varanasi', 'Noida-YEIDA', 'Kanpur', 'Agra'],
  },
  {
    id: 'GJ',
    name: 'Gujarat',
    code: 'IN-GJ',
    riskScore: 38,
    riskLevel: 'low',
    activeProjects: 41,
    delayedProjects: 6,
    capitalAtRiskCr: 2100,
    avgDelayMonths: 3.2,
    primaryBottleneck: 'Industrial Zoning Clearances Fast-Tracked',
    centerCoords: [22, 48],
    path: 'M 18,42 L 32,42 L 34,56 L 24,58 L 16,50 Z',
    topDistricts: ['Ahmedabad', 'Surat', 'Vadodara', 'Dholera SIR', 'Rajkot'],
  },
  {
    id: 'TS',
    name: 'Telangana',
    code: 'IN-TS',
    riskScore: 45,
    riskLevel: 'medium',
    activeProjects: 33,
    delayedProjects: 9,
    capitalAtRiskCr: 1870,
    avgDelayMonths: 4.6,
    primaryBottleneck: 'Dharani Portal Synchronization & Title Claims',
    centerCoords: [48, 70],
    path: 'M 44,66 L 55,65 L 56,76 L 46,78 Z',
    topDistricts: ['Hyderabad Outer', 'Warangal', 'Rangareddy', 'Karimnagar'],
  },
  {
    id: 'RJ',
    name: 'Rajasthan',
    code: 'IN-RJ',
    riskScore: 58,
    riskLevel: 'medium',
    activeProjects: 29,
    delayedProjects: 11,
    capitalAtRiskCr: 2450,
    avgDelayMonths: 6.1,
    primaryBottleneck: 'Renewable Solar Corridor Desert Land Clearances',
    centerCoords: [28, 32],
    path: 'M 22,24 L 40,24 L 42,38 L 26,42 L 20,32 Z',
    topDistricts: ['Jaipur', 'Jodhpur', 'Bikaner', 'Kota', 'Udaipur'],
  },
  {
    id: 'TN',
    name: 'Tamil Nadu',
    code: 'IN-TN',
    riskScore: 52,
    riskLevel: 'medium',
    activeProjects: 38,
    delayedProjects: 12,
    capitalAtRiskCr: 3120,
    avgDelayMonths: 5.4,
    primaryBottleneck: 'Industrial Corridor & High Density Road Widening',
    centerCoords: [44, 90],
    path: 'M 40,84 L 50,84 L 48,97 L 38,94 Z',
    topDistricts: ['Chennai Corridor', 'Coimbatore', 'Madurai', 'Salem', 'Hosur'],
  },
  {
    id: 'OD',
    name: 'Odisha',
    code: 'IN-OD',
    riskScore: 79,
    riskLevel: 'very-high',
    activeProjects: 27,
    delayedProjects: 14,
    capitalAtRiskCr: 4300,
    avgDelayMonths: 10.5,
    primaryBottleneck: 'Schedule V Tribal Land & Mining ROW Injunctions',
    centerCoords: [68, 56],
    path: 'M 62,50 L 75,52 L 74,65 L 60,62 Z',
    topDistricts: ['Bhubaneswar', 'Cuttack', 'Jharsuguda', 'Sundargarh', 'Angul'],
  },
  {
    id: 'AS',
    name: 'Assam & North East',
    code: 'IN-AS',
    riskScore: 71,
    riskLevel: 'high',
    activeProjects: 19,
    delayedProjects: 8,
    capitalAtRiskCr: 1650,
    avgDelayMonths: 8.9,
    primaryBottleneck: 'Floodplain Reclassification & Hill Council Consents',
    centerCoords: [88, 34],
    path: 'M 82,30 L 96,30 L 94,42 L 80,40 Z',
    topDistricts: ['Guwahati', 'Dibrugarh', 'Silchar', 'Nagaon'],
  },
  {
    id: 'KA',
    name: 'Karnataka',
    code: 'IN-KA',
    riskScore: 49,
    riskLevel: 'medium',
    activeProjects: 36,
    delayedProjects: 10,
    capitalAtRiskCr: 3800,
    avgDelayMonths: 5.1,
    primaryBottleneck: 'Bhoomi RTC Cross-Verification & Peripheral Ring Road',
    centerCoords: [36, 80],
    path: 'M 32,72 L 44,72 L 44,86 L 34,86 Z',
    topDistricts: ['Bengaluru Urban', 'Mysuru', 'Belagavi', 'Mangaluru'],
  },
  {
    id: 'WB',
    name: 'West Bengal',
    code: 'IN-WB',
    riskScore: 84,
    riskLevel: 'very-high',
    activeProjects: 44,
    delayedProjects: 24,
    capitalAtRiskCr: 6200,
    avgDelayMonths: 12.0,
    primaryBottleneck: 'Dense Agricultural Fragmentation & Solatium Litigation',
    centerCoords: [74, 44],
    path: 'M 70,38 L 78,38 L 78,54 L 70,50 Z',
    topDistricts: ['Kolkata Outer', 'Howrah', 'Siliguri', 'Durgapur', 'Asansol'],
  },
  {
    id: 'BR',
    name: 'Bihar',
    code: 'IN-BR',
    riskScore: 76,
    riskLevel: 'high',
    activeProjects: 31,
    delayedProjects: 16,
    capitalAtRiskCr: 3750,
    avgDelayMonths: 9.3,
    primaryBottleneck: 'Khatian Document Mismatch & Mutation Backlogs',
    centerCoords: [68, 36],
    path: 'M 62,32 L 74,32 L 72,40 L 60,40 Z',
    topDistricts: ['Patna', 'Gaya', 'Muzaffarpur', 'Bhagalpur'],
  },
  {
    id: 'AP',
    name: 'Andhra Pradesh',
    code: 'IN-AP',
    riskScore: 55,
    riskLevel: 'medium',
    activeProjects: 28,
    delayedProjects: 9,
    capitalAtRiskCr: 2900,
    avgDelayMonths: 5.8,
    primaryBottleneck: 'Capital Region Land Pooling Scheme Appeals',
    centerCoords: [48, 80],
    path: 'M 44,74 L 56,70 L 54,86 L 44,86 Z',
    topDistricts: ['Visakhapatnam', 'Vijayawada', 'Amaravati', 'Tirupati'],
  },
  {
    id: 'PB_HR',
    name: 'Punjab & Haryana',
    code: 'IN-PBHR',
    riskScore: 62,
    riskLevel: 'high',
    activeProjects: 25,
    delayedProjects: 10,
    capitalAtRiskCr: 3400,
    avgDelayMonths: 7.2,
    primaryBottleneck: 'NHAI Expressway Agricultural Land Compensation Claims',
    centerCoords: [36, 20],
    path: 'M 30,16 L 42,16 L 44,26 L 32,26 Z',
    topDistricts: ['Gurugram', 'Faridabad', 'Amritsar', 'Ludhiana'],
  },
  {
    id: 'KL',
    name: 'Kerala',
    code: 'IN-KL',
    riskScore: 73,
    riskLevel: 'high',
    activeProjects: 18,
    delayedProjects: 8,
    capitalAtRiskCr: 2800,
    avgDelayMonths: 9.0,
    primaryBottleneck: 'High Density Habitation & R&R Resettlement Packages',
    centerCoords: [38, 92],
    path: 'M 36,88 L 42,88 L 40,98 L 36,96 Z',
    topDistricts: ['Kochi', 'Thiruvananthapuram', 'Kozhikode', 'Kollam'],
  },
  {
    id: 'JK_LA',
    name: 'Jammu & Kashmir / Ladakh',
    code: 'IN-JK',
    riskScore: 42,
    riskLevel: 'medium',
    activeProjects: 14,
    delayedProjects: 3,
    capitalAtRiskCr: 1200,
    avgDelayMonths: 4.1,
    primaryBottleneck: 'Strategic Border Road Defense Clearances',
    centerCoords: [34, 10],
    path: 'M 28,4 L 46,4 L 44,16 L 28,16 Z',
    topDistricts: ['Srinagar', 'Jammu', 'Leh', 'Udhampur'],
  },
];

// Scale Level 2: District Corridors in Madhya Pradesh
export const stateDistricts = [
  {
    id: 'BPL',
    name: 'Bhopal',
    state: 'Madhya Pradesh',
    riskScore: 84,
    riskLevel: 'high',
    projectCount: 6,
    avgDelay: '9.2 months',
    leadBottleneck: 'Multiple Khasra Title Overlaps & Urban Encroachment',
    corridor: 'Smart City Outer Ring Road & NH-46 Link',
    center: { x: 50, y: 45 },
    polygon: 'M 42,38 L 58,38 L 60,52 L 44,52 Z',
  },
  {
    id: 'IND',
    name: 'Indore',
    state: 'Madhya Pradesh',
    riskScore: 62,
    riskLevel: 'medium',
    projectCount: 5,
    avgDelay: '5.8 months',
    leadBottleneck: 'Super Corridor Commercial Land Mutation Delay',
    corridor: 'Indore Metro Phase-II & SEZ Expansion',
    center: { x: 25, y: 48 },
    polygon: 'M 18,40 L 32,40 L 34,56 L 20,56 Z',
  },
  {
    id: 'DWS',
    name: 'Dewas',
    state: 'Madhya Pradesh',
    riskScore: 28,
    riskLevel: 'low',
    projectCount: 3,
    avgDelay: '2.1 months',
    leadBottleneck: 'Industrial Area Phase-IV Boundary Survey Sync',
    corridor: 'Dewas Industrial Logistic Node & Solar Park',
    center: { x: 38, y: 35 },
    polygon: 'M 32,28 L 44,28 L 44,42 L 32,42 Z',
  },
  {
    id: 'RSN',
    name: 'Raisen',
    state: 'Madhya Pradesh',
    riskScore: 88,
    riskLevel: 'high',
    projectCount: 4,
    avgDelay: '11.4 months',
    leadBottleneck: 'Schedule V FRA Gram Sabha Clearances & Forest ROW',
    corridor: 'Bhopal-Jabalpur Highway Bypass & Tribal Rehab Zone',
    center: { x: 72, y: 48 },
    polygon: 'M 60,40 L 82,40 L 80,58 L 60,58 Z',
  },
  {
    id: 'SHR',
    name: 'Sehore',
    state: 'Madhya Pradesh',
    riskScore: 35,
    riskLevel: 'low',
    projectCount: 3,
    avgDelay: '3.0 months',
    leadBottleneck: 'Agricultural Solatium Verification Rate',
    corridor: 'Narmada Water Pipeline Corridor & Agri-Logistics Hub',
    center: { x: 52, y: 72 },
    polygon: 'M 44,60 L 62,60 L 60,82 L 42,82 Z',
  },
];

// Scale Level 3: Cadastral Survey Khasra Parcels (Micro-Scale Village Polygons)
export const cadastralParcels = [
  {
    id: 'PCL-BPL-001',
    khasraNo: '234/1A',
    village: 'Kolar Khurd',
    district: 'Bhopal',
    state: 'Madhya Pradesh',
    area: '12.5 ha (30.8 Acres)',
    riskScore: 87,
    riskLevel: 'high',
    owner: 'Multiple Claimants (Govt. vs Heirs)',
    landUse: 'Residential / Agricultural Disputed',
    mutationStatus: 'Disputed In Revenue Court',
    circleRate: '₹4,200/sq.m',
    marketDemand: '₹7,800/sq.m (85% Deviation)',
    courtStay: 'Stay Active (Civil Suit No. 104/2025)',
    gramSabhaStatus: 'N/A (Urban Extension)',
    rfctlarrStatus: 'Solatium 100% Calculated, Disbursement Halted',
    estimatedDelay: '10.5 Months',
    polygonPoints: '15,20 42,18 48,36 18,38',
    color: '#dc2626',
    riskFactors: {
      ownershipDispute: 92,
      documentMismatch: 78,
      encroachment: 85,
      landUseViolation: 65,
      priceAnomaly: 45,
    },
    recommendedAction: 'Execute Lok Adalat mediation with heirs; deposit solatium in escrow pursuant to RFCTLARR Sec 77.',
  },
  {
    id: 'PCL-BPL-002',
    khasraNo: '234/1B',
    village: 'Kolar Khurd',
    district: 'Bhopal',
    state: 'Madhya Pradesh',
    area: '6.4 ha (15.8 Acres)',
    riskScore: 42,
    riskLevel: 'medium',
    owner: 'Suresh Chandra Patidar',
    landUse: 'Agricultural (Irrigated)',
    mutationStatus: 'Clean Title (Bhulekh Verified)',
    circleRate: '₹3,800/sq.m',
    marketDemand: '₹4,500/sq.m (18% Deviation)',
    courtStay: 'None',
    gramSabhaStatus: 'Approved',
    rfctlarrStatus: '200% Compensation Consent Received',
    estimatedDelay: '2.5 Months',
    polygonPoints: '48,18 78,16 82,34 50,36',
    color: '#f59e0b',
    riskFactors: {
      ownershipDispute: 25,
      documentMismatch: 35,
      encroachment: 40,
      landUseViolation: 20,
      priceAnomaly: 30,
    },
    recommendedAction: 'Issue Final Award under Section 37; schedule direct DBT compensation transfer.',
  },
  {
    id: 'PCL-IND-001',
    khasraNo: '45/2',
    village: 'Rau Gram',
    district: 'Indore',
    state: 'Madhya Pradesh',
    area: '8.2 ha (20.2 Acres)',
    riskScore: 54,
    riskLevel: 'medium',
    owner: 'Rajesh Sharma & Partners',
    landUse: 'Commercial / Warehouse Zone',
    mutationStatus: 'Commercial Conversion Pending Stamp Duty',
    circleRate: '₹9,500/sq.m',
    marketDemand: '₹14,200/sq.m (49% Deviation)',
    courtStay: 'None',
    gramSabhaStatus: 'N/A',
    rfctlarrStatus: 'Awaiting Resettlement Package Audit',
    estimatedDelay: '4.8 Months',
    polygonPoints: '18,45 45,43 42,62 15,64',
    color: '#f59e0b',
    riskFactors: {
      ownershipDispute: 30,
      documentMismatch: 72,
      encroachment: 15,
      landUseViolation: 60,
      priceAnomaly: 55,
    },
    recommendedAction: 'Expedite Revenue Inspector site inspection for commercial regularization.',
  },
  {
    id: 'PCL-DWS-001',
    khasraNo: 'Plot 78-B',
    village: 'Industrial Sector 4',
    district: 'Dewas',
    state: 'Madhya Pradesh',
    area: '45.0 ha (111 Acres)',
    riskScore: 22,
    riskLevel: 'low',
    owner: 'MP State Industrial Dev. Corp (MPIDC)',
    landUse: 'Industrial Logistic Hub',
    mutationStatus: 'Govt. Vested Land',
    circleRate: '₹2,100/sq.m',
    marketDemand: '₹2,250/sq.m (7% Deviation)',
    courtStay: 'None',
    gramSabhaStatus: 'Cleared',
    rfctlarrStatus: 'Possession Handover Ready',
    estimatedDelay: '0.8 Months',
    polygonPoints: '52,43 85,41 88,60 55,62',
    color: '#059669',
    riskFactors: {
      ownershipDispute: 10,
      documentMismatch: 15,
      encroachment: 5,
      landUseViolation: 30,
      priceAnomaly: 25,
    },
    recommendedAction: 'Proceed with boundary fencing and final gazette notification (Section 19).',
  },
  {
    id: 'PCL-RSN-001',
    khasraNo: 'Survey 112',
    village: 'Bareli Forest Range',
    district: 'Raisen',
    state: 'Madhya Pradesh',
    area: '18.7 ha (46.2 Acres)',
    riskScore: 79,
    riskLevel: 'high',
    owner: 'Tribal Community / Schedule V Gram Sabha',
    landUse: 'Forest / Agricultural Common Land',
    mutationStatus: 'Community Forest Rights (CFR) Claimed',
    circleRate: '₹1,200/sq.m',
    marketDemand: '₹1,500/sq.m (25% Deviation)',
    courtStay: 'High Court Review on FRA Compliance',
    gramSabhaStatus: 'Pending Resolution (65% Quorum Req.)',
    rfctlarrStatus: 'Tribal Rehabilitation Package (Schedule II) Incomplete',
    estimatedDelay: '11.8 Months',
    polygonPoints: '15,70 50,68 46,88 12,90',
    color: '#dc2626',
    riskFactors: {
      ownershipDispute: 85,
      documentMismatch: 60,
      encroachment: 90,
      landUseViolation: 75,
      priceAnomaly: 40,
    },
    recommendedAction: 'Convene Special Gram Sabha with Tribal Welfare Officer; finalize Schedule II R&R entitlements.',
  },
  {
    id: 'PCL-SHR-001',
    khasraNo: 'Khasra 89/1',
    village: 'Ashta Bypass',
    district: 'Sehore',
    state: 'Madhya Pradesh',
    area: '9.3 ha (23 Acres)',
    riskScore: 31,
    riskLevel: 'low',
    owner: 'Rameshwar Dayal Verma',
    landUse: 'Agricultural Double-Cropping',
    mutationStatus: 'Verified with MP Bhulekh B-1 Khasra',
    circleRate: '₹2,600/sq.m',
    marketDemand: '₹3,000/sq.m (15% Deviation)',
    courtStay: 'None',
    gramSabhaStatus: 'Approved',
    rfctlarrStatus: 'Agreement Signed for Direct Purchase',
    estimatedDelay: '1.2 Months',
    polygonPoints: '55,68 88,66 84,86 52,88',
    color: '#059669',
    riskFactors: {
      ownershipDispute: 15,
      documentMismatch: 20,
      encroachment: 12,
      landUseViolation: 22,
      priceAnomaly: 18,
    },
    recommendedAction: 'Release first installment via PFMS direct treasury dispatch.',
  },
];

