// lib/mockData.js
// All mock data for Dhara Sanket AI dashboard.
// Replace these exports with real API calls to your FastAPI backend later.

export const stats = [
  {
    id: 'total-projects',
    label: 'Total Projects',
    value: 47,
    trend: '+12%',
    trendUp: true,
    icon: 'projects',
  },
  {
    id: 'districts',
    label: 'Districts Covered',
    value: 5,
    trend: '+2',
    trendUp: true,
    icon: 'districts',
  },
  {
    id: 'land-records',
    label: 'Land Records Analyzed',
    value: '12,847',
    trend: '+1,240',
    trendUp: true,
    icon: 'records',
  },
  {
    id: 'accuracy',
    label: 'Monitoring Accuracy',
    value: '96.4%',
    trend: '+1.2%',
    trendUp: true,
    icon: 'accuracy',
  },
];

export const projects = [
  {
    id: 'PRJ-001',
    name: 'Bhopal Smart City Ring Road Extension',
    district: 'Bhopal',
    area: '245.8 ha',
    status: 'In Progress',
    risk: 'high',
    startDate: '2026-03-15',
    landRecords: 1842,
    progress: 35,
  },
  {
    id: 'PRJ-002',
    name: 'Indore Metro Phase-II Land Acquisition',
    district: 'Indore',
    area: '182.3 ha',
    status: 'In Progress',
    risk: 'medium',
    startDate: '2026-01-20',
    landRecords: 1356,
    progress: 58,
  },
  {
    id: 'PRJ-003',
    name: 'Dewas Industrial Corridor Development',
    district: 'Dewas',
    area: '520.1 ha',
    status: 'Planning',
    risk: 'low',
    startDate: '2026-06-01',
    landRecords: 2104,
    progress: 12,
  },
  {
    id: 'PRJ-004',
    name: 'Raisen Highway Bypass Construction',
    district: 'Raisen',
    area: '98.7 ha',
    status: 'In Progress',
    risk: 'high',
    startDate: '2026-02-10',
    landRecords: 876,
    progress: 42,
  },
  {
    id: 'PRJ-005',
    name: 'Sehore Agricultural Zone Reallocation',
    district: 'Sehore',
    area: '310.4 ha',
    status: 'Review',
    risk: 'medium',
    startDate: '2026-04-22',
    landRecords: 1589,
    progress: 68,
  },
  {
    id: 'PRJ-006',
    name: 'Bhopal Lake Front Urban Renewal',
    district: 'Bhopal',
    area: '75.2 ha',
    status: 'In Progress',
    risk: 'high',
    startDate: '2026-05-08',
    landRecords: 634,
    progress: 25,
  },
  {
    id: 'PRJ-007',
    name: 'Indore SEZ Phase-III Expansion',
    district: 'Indore',
    area: '420.0 ha',
    status: 'Approved',
    risk: 'low',
    startDate: '2026-07-15',
    landRecords: 2890,
    progress: 5,
  },
  {
    id: 'PRJ-008',
    name: 'Dewas Solar Park Land Acquisition',
    district: 'Dewas',
    area: '680.5 ha',
    status: 'In Progress',
    risk: 'medium',
    startDate: '2026-02-28',
    landRecords: 1245,
    progress: 51,
  },
  {
    id: 'PRJ-009',
    name: 'Raisen Tribal Rehabilitation Settlement',
    district: 'Raisen',
    area: '156.3 ha',
    status: 'Review',
    risk: 'high',
    startDate: '2026-01-05',
    landRecords: 945,
    progress: 72,
  },
  {
    id: 'PRJ-010',
    name: 'Sehore Water Pipeline Corridor',
    district: 'Sehore',
    area: '89.6 ha',
    status: 'In Progress',
    risk: 'low',
    startDate: '2026-08-01',
    landRecords: 412,
    progress: 18,
  },
  {
    id: 'PRJ-011',
    name: 'Bhopal Eastern Freight Corridor',
    district: 'Bhopal',
    area: '345.2 ha',
    status: 'Planning',
    risk: 'medium',
    startDate: '2026-09-10',
    landRecords: 1678,
    progress: 8,
  },
  {
    id: 'PRJ-012',
    name: 'Indore Riverfront Development',
    district: 'Indore',
    area: '128.9 ha',
    status: 'In Progress',
    risk: 'high',
    startDate: '2026-04-01',
    landRecords: 756,
    progress: 44,
  },
];

export const alerts = [
  {
    id: 'ALT-001',
    title: 'Ownership Dispute Detected',
    project: 'Bhopal Smart City Ring Road Extension',
    severity: 'high',
    time: '12 min ago',
    description: 'Multiple ownership claims found for Survey No. 234/1A in Kolar area.',
  },
  {
    id: 'ALT-002',
    title: 'Land Use Violation',
    project: 'Raisen Highway Bypass Construction',
    severity: 'high',
    time: '34 min ago',
    description: 'Agricultural land re-classified without proper documentation.',
  },
  {
    id: 'ALT-003',
    title: 'Encroachment Alert',
    project: 'Bhopal Lake Front Urban Renewal',
    severity: 'high',
    time: '1 hr ago',
    description: 'Unauthorized construction detected on acquired parcel BPL-045.',
  },
  {
    id: 'ALT-004',
    title: 'Document Mismatch',
    project: 'Indore Metro Phase-II Land Acquisition',
    severity: 'medium',
    time: '2 hrs ago',
    description: 'Registry records do not match revenue records for 3 parcels.',
  },
  {
    id: 'ALT-005',
    title: 'Price Anomaly Flagged',
    project: 'Sehore Agricultural Zone Reallocation',
    severity: 'medium',
    time: '3 hrs ago',
    description: 'Market value deviates by 42% from government circle rate.',
  },
  {
    id: 'ALT-006',
    title: 'Survey Boundary Update',
    project: 'Dewas Industrial Corridor Development',
    severity: 'low',
    time: '5 hrs ago',
    description: 'Digital survey boundaries updated for 12 parcels in Sector 4.',
  },
  {
    id: 'ALT-007',
    title: 'Compliance Check Passed',
    project: 'Indore SEZ Phase-III Expansion',
    severity: 'low',
    time: '6 hrs ago',
    description: 'Environmental clearance documents verified successfully.',
  },
  {
    id: 'ALT-008',
    title: 'Tribal Land Classification Issue',
    project: 'Raisen Tribal Rehabilitation Settlement',
    severity: 'high',
    time: '8 hrs ago',
    description: 'Schedule V land parcels require additional governmental approval.',
  },
];

export const riskDistribution = {
  high: 5,
  medium: 3,
  low: 4,
};

export const projectsByDistrict = [
  { district: 'Bhopal', count: 3 },
  { district: 'Indore', count: 3 },
  { district: 'Dewas', count: 2 },
  { district: 'Raisen', count: 2 },
  { district: 'Sehore', count: 2 },
];

export const projectTrend = [
  { month: 'Jan', count: 2 },
  { month: 'Feb', count: 4 },
  { month: 'Mar', count: 5 },
  { month: 'Apr', count: 7 },
  { month: 'May', count: 8 },
  { month: 'Jun', count: 9 },
  { month: 'Jul', count: 10 },
  { month: 'Aug', count: 11 },
  { month: 'Sep', count: 12 },
];

export const hotspots = [
  { x: 55, y: 35, risk: 'high', label: 'Bhopal North', district: 'Bhopal' },
  { x: 48, y: 50, risk: 'high', label: 'Bhopal Central', district: 'Bhopal' },
  { x: 60, y: 60, risk: 'medium', label: 'Bhopal East', district: 'Bhopal' },
  { x: 20, y: 40, risk: 'high', label: 'Indore West', district: 'Indore' },
  { x: 28, y: 55, risk: 'medium', label: 'Indore South', district: 'Indore' },
  { x: 15, y: 30, risk: 'low', label: 'Indore North', district: 'Indore' },
  { x: 38, y: 25, risk: 'low', label: 'Dewas Central', district: 'Dewas' },
  { x: 42, y: 35, risk: 'medium', label: 'Dewas East', district: 'Dewas' },
  { x: 68, y: 40, risk: 'high', label: 'Raisen West', district: 'Raisen' },
  { x: 75, y: 55, risk: 'high', label: 'Raisen South', district: 'Raisen' },
  { x: 50, y: 72, risk: 'low', label: 'Sehore Central', district: 'Sehore' },
  { x: 58, y: 80, risk: 'low', label: 'Sehore South', district: 'Sehore' },
];

export const parcels = [
  {
    id: 'PCL-BPL-001',
    name: 'Survey No. 234/1A, Kolar',
    district: 'Bhopal',
    area: '12.5 ha',
    riskScore: 87,
    riskFactors: {
      ownershipDispute: 92,
      documentMismatch: 78,
      encroachment: 85,
      landUseViolation: 65,
      priceAnomaly: 45,
    },
    owner: 'Multiple Claimants',
    landUse: 'Residential / Agricultural (Disputed)',
    lastUpdated: '2026-09-15',
  },
  {
    id: 'PCL-IND-001',
    name: 'Khasra No. 45/2, Rau',
    district: 'Indore',
    area: '8.2 ha',
    riskScore: 54,
    riskFactors: {
      ownershipDispute: 30,
      documentMismatch: 72,
      encroachment: 15,
      landUseViolation: 60,
      priceAnomaly: 55,
    },
    owner: 'Rajesh Sharma',
    landUse: 'Commercial',
    lastUpdated: '2026-09-14',
  },
  {
    id: 'PCL-DWS-001',
    name: 'Plot 78-B, Industrial Area',
    district: 'Dewas',
    area: '45.0 ha',
    riskScore: 22,
    riskFactors: {
      ownershipDispute: 10,
      documentMismatch: 15,
      encroachment: 5,
      landUseViolation: 30,
      priceAnomaly: 25,
    },
    owner: 'MP State Industrial Dev. Corp.',
    landUse: 'Industrial',
    lastUpdated: '2026-09-13',
  },
  {
    id: 'PCL-RSN-001',
    name: 'Survey No. 112, Bareli',
    district: 'Raisen',
    area: '18.7 ha',
    riskScore: 79,
    riskFactors: {
      ownershipDispute: 85,
      documentMismatch: 60,
      encroachment: 90,
      landUseViolation: 75,
      priceAnomaly: 40,
    },
    owner: 'Tribal Community (Schedule V)',
    landUse: 'Forest / Agricultural',
    lastUpdated: '2026-09-12',
  },
];

export const reportStats = [
  { label: 'Total Reports Generated', value: 128, icon: 'report' },
  { label: 'Alerts Resolved', value: 89, icon: 'resolved' },
  { label: 'Pending Reviews', value: 14, icon: 'pending' },
  { label: 'Compliance Score', value: '91.2%', icon: 'compliance' },
];
